Add chmod to auto perm script
truecharts/library-charts pull request #451
Opened 2023-06-02 21:12 UTC by stavros-k

**Description**

⚒️ Fixes  # 

**⚙️ Type of change**

- [ ] ⚙️ Feature/App addition
- [ ] 🪛 Bugfix
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🔃 Refactor of current code

**🧪 How Has This Been Tested?**

**📃 Notes:**

**✔️ Checklist:**

- [ ] ⚖️ My code follows the style guidelines of this project
- [ ] 👀 I have performed a self-review of my own code
- [ ] #️⃣ I have commented my code, particularly in hard-to-understand areas
- [ ] 📄 I have made corresponding changes to the documentation
- [ ] ⚠️ My changes generate no new warnings
- [ ] 🧪 I have added tests to this description that prove my fix is effective or that my feature works
- [ ] ⬆️ I increased versions for any altered app according to semantic versioning

**➕ App addition**

If this PR is an app addition please make sure you have done the following.

- [ ] 🪞 I have opened a PR on [truecharts/containers](https://github.com/truecharts/containers) adding the container to TrueCharts mirror repo.
- [ ] 🖼️ I have added an icon in the Chart's root directory called `icon.png`

---

_Please don't blindly check all the boxes. Read them and only check those that apply.
Those checkboxes are there for the reviewer to see what is this all about and
the status of this PR with a quick glance._

2023-06-02 21:36 UTC, Ornias1993 requested changes
- We should utilise the nfs4xdr_winacl equivalent for chmod on SCALE.
- Could you restyle the responses/warnings in console a tad? I think the iX log output is a tad cleaner...

2023-06-02 21:44 UTC, Ornias1993 commented on library/common/templates/lib/util/_autoperms.tpl
> +              chmod {{ $hpm.chmod }} /mounts/{{ $name }} || echo "Failed setting permissions using chmod..."
The own seems to be recursive while the chmod does not...
Maybe we want recursive as an option? 

though that might mean we want to indent those three settings under a dict like this:
```
autoPermissions:
  chown: true
  chmod: 775
  recursive: true
  ```

2023-06-02 21:49 UTC, stavros-k commented on library/common/templates/lib/util/_autoperms.tpl
> +              chmod {{ $hpm.chmod }} /mounts/{{ $name }} || echo "Failed setting permissions using chmod..."
Actually there are more things to do here...
We can only apply chmod/chown in hostPath, due to how volumes are rendered .in the container

While chown is not needed in pvc, chmod does (in rare cases, see Nextcloud).

2023-06-02 21:49 UTC, stavros-k commented on library/common/templates/lib/util/_autoperms.tpl
> +              chmod {{ $hpm.chmod }} /mounts/{{ $name }} || echo "Failed setting permissions using chmod..."
> The own seems to be recursive while the chmod does not... Maybe we want recursive as an option?
> 
> though that might mean we want to indent those three settings under a dict like this:
> 
> ```
> autoPermissions:
>   chown: true
>   chmod: 775
>   recursive: true
> ```

But I'm cool with the dict

2023-06-02 21:57 UTC, Ornias1993 commented on library/common/templates/lib/util/_autoperms.tpl
> +              chmod {{ $hpm.chmod }} /mounts/{{ $name }} || echo "Failed setting permissions using chmod..."
> Actually there are more things to do here... We can only apply chmod/chown in hostPath, due to how volumes are rendered .in the container
> 
> While chown is not needed in pvc, chmod does (in rare cases, see Nextcloud).

Fair pont there indeed!
Maybe split the logic?

2023-06-02 22:08 UTC, Ornias1993 commented on library/common/templates/lib/util/_autoperms.tpl
> +              chmod {{ $hpm.chmod }} /mounts/{{ $name }} || echo "Failed setting permissions using chmod..."
Agreed :)

2023-06-02 22:14 UTC, stavros-k commented
> * We should utilise the nfs4xdr_winacl equivalent for chmod on SCALE.
> * Could you restyle the responses/warnings in console a tad? I think the iX log output is a tad cleaner...

What are the equivalent of chmod in winacl?

Will do the logging too

2023-06-03 10:51 UTC, Ornias1993 commented
> > * We should utilise the nfs4xdr_winacl equivalent for chmod on SCALE.
> > * Could you restyle the responses/warnings in console a tad? I think the iX log output is a tad cleaner...
> 
> What are the equivalent of chmod in winacl?
> 
> Will do the logging too

You can ask caleb if you like :)

2023-06-03 11:13 UTC, Ornias1993 approved these changes

2023-06-03 11:37 UTC, merged