fix(common): Bugfixes on codeserver ingress
truecharts/library-charts pull request #615
Opened 2023-11-21 16:19 UTC by RobReus

**Description**
The codeserver ingress uses a non existent include to get the fullname. It also does not set a name for the ingress, causing the resulting ingress resource have no name which kubernetes does not accept. It also uses the wrong namespace for middleware when no other regular ingresses are configured due to the operator verification only checking `.Values.ingress`.

**⚙️ Type of change**

- [ ] ⚙️ Feature/App addition
- [X] 🪛 Bugfix
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🔃 Refactor of current code

**🧪 How Has This Been Tested?**
Applying the fixes locally and running the updated code. The codeserver ingress got deployed without problems and worked perfectly.

**📃 Notes:**

**✔️ Checklist:**

- [X] ⚖️ My code follows the style guidelines of this project
- [X] 👀 I have performed a self-review of my own code
- [ ] #️⃣ I have commented my code, particularly in hard-to-understand areas
- [ ] 📄 I have made corresponding changes to the documentation
- [ ] ⚠️ My changes generate no new warnings
- [ ] 🧪 I have added tests to this description that prove my fix is effective or that my feature works
- [ ] ⬆️ I increased versions for any altered app according to semantic versioning

**➕ App addition**

If this PR is an app addition please make sure you have done the following.

- [ ] 🪞 I have opened a PR on [truecharts/containers](https://github.com/truecharts/containers) adding the container to TrueCharts mirror repo.
- [ ] 🖼️ I have added an icon in the Chart's root directory called `icon.png`

---

_Please don't blindly check all the boxes. Read them and only check those that apply.
Those checkboxes are there for the reviewer to see what is this all about and
the status of this PR with a quick glance._

2023-11-21 16:36 UTC, Ornias1993 requested changes
it might be best to append .Values.ingress instead of directly calling the ingressClass.

2023-11-21 16:42 UTC, RobReus commented
> it might be best to append .Values.ingress instead of directly calling the ingressClass.

I was thinking something similar, but I wanted to keep this change small as I also noticed there is an open issue to refactor ingress (#557) altogether. It would also require bigger changes as the operator verification happens _before_ the codeserver templates are included within the init loader.

2023-11-21 18:16 UTC, Ornias1993 commented
> > it might be best to append .Values.ingress instead of directly calling the ingressClass.
> 
> I was thinking something similar, but I wanted to keep this change small as I also noticed there is an open issue to refactor ingress (#557) altogether. It would also require bigger changes as the operator verification happens _before_ the codeserver templates are included within the init loader.

- Ingress refactor does not mean values.yaml will change, even so it's not likely to affect this.
- operator verification can be removed, thats already planned for another refactor that's unrelated.

2023-11-21 18:25 UTC, RobReus commented
> > > it might be best to append .Values.ingress instead of directly calling the ingressClass.
> > 
> > 
> > I was thinking something similar, but I wanted to keep this change small as I also noticed there is an open issue to refactor ingress (#557) altogether. It would also require bigger changes as the operator verification happens _before_ the codeserver templates are included within the init loader.
> 
> * Ingress refactor does not mean values.yaml will change, even so it's not likely to affect this.
> * operator verification can be removed, thats already planned for another refactor that's unrelated.

Since the ingress refactor issue has no description at all, its hard to know what exactly is meant by it and what will be refactored. But if it will not affect the values at all, it should indeed not be a problem.

I can make the changes to add the codeserver ingress to the main ingress dict instead of calling the class directly, but the code will not work or be able to be tested as long as the ingress class is not modified. Currently the ingress class determines the middleware namespace by checking whether or not traefik is installed, which is determined by the operator verification.

What do you propose I do with this PR till the above changes are performed? Will the ingress refactor perhaps provide alternative ways to deal with ingresses that are more elegant than just appending items to the dict? Or will that be the way to do it going forward?

2023-11-21 18:30 UTC, Ornias1993 commented
> > > > it might be best to append .Values.ingress instead of directly calling the ingressClass.
> > > 
> > > 
> > > I was thinking something similar, but I wanted to keep this change small as I also noticed there is an open issue to refactor ingress (#557) altogether. It would also require bigger changes as the operator verification happens _before_ the codeserver templates are included within the init loader.
> > 
> > 
> > 
> > * Ingress refactor does not mean values.yaml will change, even so it's not likely to affect this.
> > * operator verification can be removed, thats already planned for another refactor that's unrelated.
> 
> Since the ingress refactor issue has no description at all, its hard to know what exactly is meant by it and what will be refactored. But if it will not affect the values at all, it should indeed not be a problem.
> 
> I will make the changes and then request a new review.

It doesn't have description because it's just there for the maintainer tracker, it's which is not intended for anyone else.

2023-11-22 09:09 UTC, RobReus commented
@Ornias1993 The proposed change will not work in the current codebase of common. The reason for this is the `traefik` dict not existing under the `operator` key in the values. Due to this, the traefik namespace cannot be determined in the ingress class, see:
```
  {{- $mddwrNamespace := "tc-system" -}}
  {{- if $.Values.operator.traefik -}}
    {{- if $.Values.operator.traefik.namespace -}}
      {{- $mddwrNamespace = $.Values.operator.traefik.namespace -}}
    {{- end -}}
  {{- end -}}
```
https://github.com/truecharts/library-charts/blob/71f885def52156802a878beaab042640c47919d0/library/common/templates/class/_ingress.tpl#L31C3-L31C3

Since hardcoding the namespace name would be a bad idea, we would still rely on the operator verification for the time being to set these values. Since the operator verification happens _before_ the codeserver template is executed, in the event codeserver will be the only ingress, the traefik operator values will never be set as the ingress will only be appened after the fact. So in the current state of the common code, it would not be feasible to remove the direct call to the ingress class.

What are your thoughts on this?

2023-11-22 21:48 UTC, Ornias1993 commented
> @Ornias1993 The proposed change will not work in the current codebase of common. The reason for this is the `traefik` dict not existing under the `operator` key in the values. Due to this, the traefik namespace cannot be determined in the ingress class, see:
> 
> ```
>   {{- $mddwrNamespace := "tc-system" -}}
>   {{- if $.Values.operator.traefik -}}
>     {{- if $.Values.operator.traefik.namespace -}}
>       {{- $mddwrNamespace = $.Values.operator.traefik.namespace -}}
>     {{- end -}}
>   {{- end -}}
> ```
> 
> https://github.com/truecharts/library-charts/blob/71f885def52156802a878beaab042640c47919d0/library/common/templates/class/_ingress.tpl#L31C3-L31C3
> 
> Since hardcoding the namespace name would be a bad idea, we would still rely on the operator verification for the time being to set these values. Since the operator verification happens _before_ the codeserver template is executed, in the event codeserver will be the only ingress, the traefik operator values will never be set as the ingress will only be appened after the fact. So in the current state of the common code, it would not be feasible to remove the direct call to the ingress class.
> 
> What are your thoughts on this?

This PR and you have nothing to do with anything related to operators, please ignore everything operator related.
It won't be affected or touch this PR.

2023-11-22 21:50 UTC, Ornias1993 commented on library/common/templates/lib/util/_verify_operator.tpl
> +    {{- end -}}
```suggestion

```
We don't want you doing anything outside of the /addons or /loader folders in this PR

2023-11-22 22:24 UTC, merged