Volsync tests
truecharts/library-charts pull request #801
Opened 2024-04-30 07:56 UTC by stavros-k

**Description**

⚒️ Fixes  # 

**⚙️ Type of change**

- [ ] ⚙️ Feature/App addition
- [ ] 🪛 Bugfix
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🔃 Refactor of current code

**🧪 How Has This Been Tested?**

**📃 Notes:**

**✔️ Checklist:**

- [ ] ⚖️ My code follows the style guidelines of this project
- [ ] 👀 I have performed a self-review of my own code
- [ ] #️⃣ I have commented my code, particularly in hard-to-understand areas
- [ ] 📄 I have made corresponding changes to the documentation
- [ ] ⚠️ My changes generate no new warnings
- [ ] 🧪 I have added tests to this description that prove my fix is effective or that my feature works
- [ ] ⬆️ I increased versions for any altered app according to semantic versioning
- [ ] I made sure the title starts with `feat(chart-name):`, `fix(chart-name):` or `chore(chart-name):`

**➕ App addition**

If this PR is an app addition please make sure you have done the following.

- [ ] 🖼️ I have added an icon in the Chart's root directory called `icon.png`

---

_Please don't blindly check all the boxes. Read them and only check those that apply.
Those checkboxes are there for the reviewer to see what is this all about and
the status of this PR with a quick glance._

2024-04-30 07:56 UTC, stavros-k commented on library/common/templates/spawner/_pvc.tpl
> -            {{- $resticpassword := ( $credentials.encrKey | default $.Release.Name ) -}}
We have validation in place to not allow empty encrKey

2024-04-30 07:57 UTC, stavros-k commented on library/common/templates/spawner/_pvc.tpl
> -            {{- $resticrepository = printf "s3:%s/%s/%s/%s/volsync/%s-volsync-%s" $credentials.url $credentials.bucket ( $credentials.path | trimSuffix "/" ) $.Release.Name $objectData.shortName $vol
Splitted this in 2 parts, baseRepo and repoSuffix.
We inject the path in the middle if we have one

2024-04-30 09:33 UTC, Ornias1993 requested changes
maybe also just nuke google and azure completely while at it?

2024-04-30 09:35 UTC, Ornias1993 commented on library/common/templates/spawner/_pvc.tpl
> -            {{- $resticrepository = printf "s3:%s/%s/%s/%s/volsync/%s-volsync-%s" $credentials.url $credentials.bucket ( $credentials.path | trimSuffix "/" ) $.Release.Name $objectData.shortName $vol
Lot cleaner indeed, I had it pretty garbage code quality so I could test if it actually worked correctly.
But this is better indeed!

2024-04-30 09:35 UTC, Ornias1993 commented on library/common/templates/spawner/_pvc.tpl
> -            {{- $resticpassword := ( $credentials.encrKey | default $.Release.Name ) -}}
I noticed after that change, lets keep it "not allowed to be empty" indeed.

2024-04-30 09:37 UTC, Ornias1993 commented on library/common/templates/spawner/_pvc.tpl
> -            {{- $resticrepository = printf "s3:%s/%s/%s/%s/volsync/%s-volsync-%s" $credentials.url $credentials.bucket ( $credentials.path | trimSuffix "/" ) $.Release.Name $objectData.shortName $vol
I'm inclined to say we should set `.Values.credentials.something.baseRepo`
Somewhere earily in the pipeline.

I noticed most things just use the baseurl anyway

2024-05-01 09:22 UTC, stavros-k commented on library/common-test/ci/credentials-values.yaml
>  credentials:
btw those are ignored currently, as we don't have neither any volsync or a cnpg using them.

Should I add something there?

(Same for credList)

2024-05-01 09:23 UTC, stavros-k commented on library/common-test/ci/credentials-values.yaml
>  credentials:
On the other hand, we already have a volsync ci values file.

2024-05-01 09:39 UTC, stavros-k commented on library/common/templates/spawner/_pvc.tpl
> -            {{- $resticrepository = printf "s3:%s/%s/%s/%s/volsync/%s-volsync-%s" $credentials.url $credentials.bucket ( $credentials.path | trimSuffix "/" ) $.Release.Name $objectData.shortName $vol
cnpg looks like it uses 
`s3://$bucket/...`
and the url on another field

While volsync uses `s3:$url/$bucket`

Is there any other place we use the base repo?

2024-05-01 09:41 UTC, stavros-k commented
I've gone over the changed files, I think it is fine, but a second look wouldn't be bad

2024-05-01 10:21 UTC, Ornias1993 commented on library/common/templates/spawner/_pvc.tpl
> -            {{- $resticrepository = printf "s3:%s/%s/%s/%s/volsync/%s-volsync-%s" $credentials.url $credentials.bucket ( $credentials.path | trimSuffix "/" ) $.Release.Name $objectData.shortName $vol
ahh yes my bad.

2024-05-01 10:26 UTC, merged